import{a as y,S,i as m}from"./assets/vendor-lpw1wAPO.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const f=r=>` <li class="gallery-card">
      <a href="${r.largeImageURL}" class="gallery-link">
        <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p><strong>Likes:</strong> ${r.likes}</p>
        <p><strong>Views:</strong> ${r.views}</p>
        <p><strong>Comments:</strong> ${r.comments}</p>
        <p><strong>Downloads:</strong> ${r.downloads}</p>
      </div>
    </li>`;y.defaults.baseURL="https://pixabay.com";const L=(r,e)=>{const a={params:{q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15,key:"45516244-7009a6d8a44aa98a2987db7ac"}};return y.get("/api/",a)},c=document.querySelector(".search-form"),i=document.querySelector(".gallery"),g=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");let d="",h=1,u=0,l=0,b=0,v=new S(".gallery a",{captionsData:"alt",captionDelay:250});const q=async r=>{try{if(r.preventDefault(),d=c.elements.user_query.value.trim(),!d){i.innerHTML="",c.reset();return}h=1,u=0,l=0,i.innerHTML="",c.reset(),g.classList.remove("is-hidden");const e=await L(d,h);if(e.data.hits.length===0){m.error({message:"There are no images matching your search query. Please try again!",position:"topRight"}),n.classList.add("is-hidden"),g.classList.add("is-hidden");return}u=e.data.totalHits,l=e.data.hits.length;const a=e.data.hits.map(t=>f(t)).join("");i.insertAdjacentHTML("beforeend",a),v.refresh(),b=i.querySelector("li").getBoundingClientRect().height,l<u?n.classList.remove("is-hidden"):(m.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.classList.add("is-hidden"))}catch(e){console.log(e)}finally{g.classList.add("is-hidden")}},w=async r=>{try{h++;const e=await L(d,h);l+=e.data.hits.length;const a=e.data.hits.map(o=>f(o)).join("");i.insertAdjacentHTML("beforeend",a),v.refresh(),scrollBy({top:b*2,behavior:"smooth"}),l>=u&&(m.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.classList.add("is-hidden"))}catch(e){console.log(e)}};c.addEventListener("submit",q);n.addEventListener("click",w);
//# sourceMappingURL=commonHelpers.js.map
